# Generated by Django 6.1 on 2026-08-14 12:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrun',
            name='entrada',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='resultado',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
