# Generated by Django 6.1 on 2026-08-14 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(choices=[('self_service', 'Self-service'), ('consultoria', 'Consultoria (Fase 2)'), ('licenca_consultor', 'Licença por consultor (Fase 3)')], max_length=25, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Período de teste'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('cancelada', 'Cancelada')], default='trial', max_length=20)),
                ('inicio', models.DateField()),
                ('fim_periodo_atual', models.DateField(blank=True, null=True)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=120)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='households.household')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='billing.plan')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
    ]
