# Generated by Django 6.1 on 2026-08-19 07:50

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('households', '0006_renomear_modo_lancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-criado_em'], 'verbose_name': 'assinatura', 'verbose_name_plural': 'assinaturas'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='fim_periodo_atual',
        ),
        migrations.AddField(
            model_name='plan',
            name='preco_anual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Em branco quando o plano não é vendido no anual.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelada_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='carencia_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='proxima_cobranca',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_termina_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(blank=True, help_text='Vazio enquanto a cobrança é feita manualmente.', max_length=40),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Período de teste'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente (em carência)'), ('suspensa', 'Suspensa por falta de pagamento'), ('cancelada', 'Cancelada')], default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='DadosFiscais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('documento', models.CharField(help_text='CPF ou CNPJ, somente números.', max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=80)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_fiscais', to='households.household')),
            ],
            options={
                'verbose_name': 'dados fiscais',
                'verbose_name_plural': 'dados fiscais',
            },
        ),
    ]
