# Generated by Django 6.1 on 2026-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_planos_iniciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['ordem', 'preco_mensal'], 'verbose_name': 'plano', 'verbose_name_plural': 'planos'},
        ),
        migrations.AddField(
            model_name='plan',
            name='disponivel',
            field=models.BooleanField(default=False, help_text="Pode ser assinado agora. Falso = anunciado como 'em breve'."),
        ),
        migrations.AddField(
            model_name='plan',
            name='meses_promocionais',
            field=models.PositiveSmallIntegerField(default=0, help_text='Por quantos meses o preço promocional vale.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='recursos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promocao_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Aparece na vitrine.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='codigo',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('consultor', 'Com consultor')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Valor cheio, após a promoção.', max_digits=10),
        ),
    ]
