# Generated by Django 6.1 on 2026-08-14 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('plataforma', 'Plataforma (clientes self-service)'), ('consultor', 'Workspace de consultor')], default='consultor', max_length=20)),
                ('marca_logo_url', models.URLField(blank=True)),
                ('marca_cor_primaria', models.CharField(blank=True, max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
        ),
    ]
