# Generated by Django 6.1 on 2026-08-14 12:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(choices=[('renda_trabalho', 'Renda do trabalho'), ('renda_investimento', 'Renda de investimentos'), ('outra_receita', 'Outra receita'), ('despesa_fixa', 'Despesa fixa'), ('despesa_variavel', 'Despesa variável'), ('investimento', 'Investimento/aporte'), ('divida', 'Pagamento de dívida'), ('imposto', 'Impostos')], max_length=25)),
                ('descricao', models.CharField(max_length=180)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_orcado', models.DecimalField(decimal_places=2, default=0, help_text='Comparativo orçado x realizado (seção 3.2).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='households.household')),
                ('membro', models.ForeignKey(blank=True, help_text='Nulo = lançamento compartilhado pela família.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='households.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'lançamento de fluxo de caixa',
                'verbose_name_plural': 'lançamentos de fluxo de caixa',
                'ordering': ['-ano', '-mes', 'descricao'],
                'indexes': [models.Index(fields=['household', 'ano', 'mes'], name='cashflow_ca_househo_6decf0_idx')],
            },
        ),
    ]
