# Generated by Django 6.1 on 2026-08-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('households', '0002_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='fonte_renda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='households.incomesource'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='regime',
            field=models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ (Simples Nacional)'), ('autonomo', 'Autônomo (RPA/Carnê-Leão)')], help_text='Regime tributário da receita. Alimenta o simulador PJ x CLT.', max_length=20),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='tipo_renda',
            field=models.CharField(blank=True, choices=[('plantao', 'Plantão'), ('clt_hospitalar', 'CLT hospitalar'), ('pj_consultorio', 'PJ / consultório'), ('aluguel', 'Aluguel'), ('outra', 'Outra')], help_text='Plantão, CLT hospitalar, PJ/consultório...', max_length=20),
        ),
    ]
