# Generated by Django 6.1 on 2026-08-18 22:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_cashflowentry_fonte_renda_cashflowentry_regime_and_more'),
        ('households', '0005_alter_incomesource_modo_lancamento'),
        ('tenancy', '0002_tenant_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('despesa_fixa', 'Despesa fixa'), ('despesa_variavel', 'Despesa variável'), ('investimento', 'Investimento/aporte'), ('divida', 'Pagamento de dívida'), ('imposto', 'Impostos')], default='despesa_fixa', max_length=25)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('divida', models.ForeignKey(blank=True, help_text='Vincula a parcela ao financiamento correspondente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_recorrentes', to='households.debt')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_recorrentes', to='households.household')),
                ('membro', models.ForeignKey(blank=True, help_text='Nulo = despesa compartilhada pela família.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_recorrentes', to='households.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'despesa recorrente',
                'verbose_name_plural': 'despesas recorrentes',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='despesa_recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='cashflow.recurringexpense'),
        ),
    ]
