# Generated by Django 6.1 on 2026-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_recurringexpense_cashflowentry_despesa_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor antes da retenção na fonte, quando houver.', max_digits=12, null=True),
        ),
    ]
