# Generated by Django 6.1 on 2026-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_cashflowentry_valor_bruto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowentry',
            name='tipo_renda',
            field=models.CharField(blank=True, choices=[('plantao', 'Serviço avulso'), ('clt_hospitalar', 'Salário CLT'), ('pj_consultorio', 'PJ / negócio próprio'), ('aluguel', 'Aluguel'), ('outra', 'Outra')], help_text='Serviço avulso, salário CLT, PJ/negócio próprio...', max_length=20),
        ),
    ]
