# Generated by Django 6.1 on 2026-08-14 12:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex.: Família Souza', max_length=180)),
                ('modo', models.CharField(choices=[('self_service', 'Self-service'), ('consultoria', 'Consultoria')], default='self_service', max_length=20)),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'União estável'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='solteiro', max_length=20)),
                ('regime_bens', models.CharField(choices=[('comunhao_parcial', 'Comunhão parcial'), ('comunhao_universal', 'Comunhão universal'), ('separacao_total', 'Separação total'), ('participacao_final', 'Participação final nos aquestos'), ('nao_aplicavel', 'Não aplicável')], default='nao_aplicavel', max_length=25)),
                ('onboarding_concluido_em', models.DateTimeField(blank=True, null=True)),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'núcleo familiar',
                'verbose_name_plural': 'núcleos familiares',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('conjuge', 'Cônjuge/companheiro(a)'), ('dependente', 'Dependente')], max_length=20)),
                ('nome', models.CharField(max_length=180)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('evento_futuro', models.CharField(blank=True, max_length=180)),
                ('evento_futuro_ano', models.PositiveIntegerField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='households.household')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
            },
        ),
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('aposentadoria', 'Aposentadoria'), ('imovel', 'Compra de imóvel'), ('faculdade_filhos', 'Faculdade dos filhos'), ('sucessao', 'Sucessão patrimonial'), ('reserva', 'Reserva de emergência'), ('outro', 'Outro')], max_length=25)),
                ('descricao', models.CharField(max_length=255)),
                ('horizonte_anos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='households.household')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
                ('membro', models.ForeignKey(blank=True, help_text='Nulo quando o objetivo é do casal/família.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='households.member')),
            ],
            options={
                'verbose_name': 'objetivo de vida',
                'verbose_name_plural': 'objetivos de vida',
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('plantao', 'Plantão'), ('clt_hospitalar', 'CLT hospitalar'), ('pj_consultorio', 'PJ / consultório'), ('aluguel', 'Aluguel'), ('outra', 'Outra')], max_length=20)),
                ('regime', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ (Simples Nacional)'), ('autonomo', 'Autônomo (RPA/Carnê-Leão)')], max_length=20)),
                ('valor_medio_mensal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('variabilidade_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Oscilação esperada em torno do valor médio, em %.', max_digits=5)),
                ('ativa', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_renda', to='households.household')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_renda', to='households.member')),
            ],
            options={
                'verbose_name': 'fonte de renda',
                'verbose_name_plural': 'fontes de renda',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('financiamento_imovel', 'Financiamento de imóvel'), ('financiamento_veiculo', 'Financiamento de veículo'), ('consultorio', 'Consultório'), ('equipamento', 'Equipamento'), ('residencia_medica', 'Financiamento de residência médica'), ('cartao', 'Cartão de crédito'), ('outra', 'Outra')], max_length=25)),
                ('descricao', models.CharField(max_length=180)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('taxa_juros_mensal', models.DecimalField(decimal_places=3, default=0, help_text='Em % ao mês.', max_digits=6)),
                ('parcelas_restantes', models.PositiveIntegerField(default=0)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('titularidade', models.CharField(choices=[('titular', 'Titular'), ('conjuge', 'Cônjuge'), ('conjunto', 'Conjunto/comunhão')], default='titular', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='households.household')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas', to='households.member')),
            ],
            options={
                'verbose_name': 'dívida',
                'verbose_name_plural': 'dívidas',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('imovel', 'Imóvel'), ('veiculo', 'Veículo'), ('aplicacao', 'Aplicação financeira'), ('participacao', 'Participação societária'), ('previdencia', 'Previdência'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=180)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('titularidade', models.CharField(choices=[('titular', 'Titular'), ('conjuge', 'Cônjuge'), ('conjunto', 'Conjunto/comunhão')], default='titular', max_length=20)),
                ('detentor_juridico', models.CharField(blank=True, help_text='Pessoa física, PJ, holding...', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='households.household')),
                ('membro', models.ForeignKey(blank=True, help_text='Preenchido quando o bem é individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='households.member')),
            ],
            options={
                'verbose_name': 'patrimônio',
                'verbose_name_plural': 'patrimônios',
            },
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['tenant', 'modo'], name='households__tenant__9b1941_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'titular')), fields=('household',), name='unico_titular_por_household'),
        ),
    ]
