# Generated by Django 6.1 on 2026-08-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'membro', 'verbose_name_plural': 'membros'},
        ),
    ]
