# Generated by Django 6.1 on 2026-08-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='data_primeira_parcela',
            field=models.DateField(blank=True, help_text='Permite calcular quantas parcelas já foram pagas.', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='parcelas_totais',
            field=models.PositiveIntegerField(default=0, help_text='Prazo contratado, em meses.'),
        ),
        migrations.AddField(
            model_name='debt',
            name='sistema',
            field=models.CharField(choices=[('price', 'Price (parcela fixa)'), ('sac', 'SAC (parcela decrescente)')], default='price', help_text='Price é o padrão em financiamento de veículo; SAC, em imóvel pela Caixa.', max_length=10),
        ),
        migrations.AddField(
            model_name='debt',
            name='valor_financiado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor original do contrato, antes de qualquer pagamento.', max_digits=14),
        ),
    ]
