# Generated by Django 6.1 on 2026-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_debt_data_primeira_parcela_debt_parcelas_totais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='modo_lancamento',
            field=models.CharField(choices=[('media', 'Valor médio mensal'), ('mensal', 'Lançar mês a mês')], default='media', max_length=10),
        ),
    ]
