# Generated by Django 6.1 on 2026-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_incomesource_modo_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='modo_lancamento',
            field=models.CharField(choices=[('fixa', 'Fixa (mesmo valor todo mês)'), ('variavel', 'Variável (lançada mês a mês)')], default='fixa', max_length=10),
        ),
    ]
