# Generated by Django 6.1 on 2026-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_renomear_modo_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='valor_e_bruto',
            field=models.BooleanField(default=True, help_text='No CLT, indica que o valor informado é o de antes dos descontos.'),
        ),
    ]
