# Generated by Django 6.1 on 2026-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_incomesource_valor_e_bruto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='tipo',
            field=models.CharField(choices=[('financiamento_imovel', 'Financiamento de imóvel'), ('financiamento_veiculo', 'Financiamento de veículo'), ('consultorio', 'Negócio próprio'), ('equipamento', 'Equipamento'), ('residencia_medica', 'Financiamento de estudos'), ('cartao', 'Cartão de crédito'), ('outra', 'Outra')], max_length=25),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='tipo',
            field=models.CharField(choices=[('plantao', 'Serviço avulso'), ('clt_hospitalar', 'Salário CLT'), ('pj_consultorio', 'PJ / negócio próprio'), ('aluguel', 'Aluguel'), ('outra', 'Outra')], max_length=20),
        ),
    ]
