# Generated by Django 6.1 on 2026-08-14 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=180)),
                ('selic_meta_percentual', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('selic_variacao_mes', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ipca_mes_percentual', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ipca_12m_percentual', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fonte_dados', models.CharField(default='Banco Central do Brasil (SGS)', max_length=120)),
                ('secoes', models.JSONField(default=list)),
                ('glossario', models.JSONField(default=list)),
                ('disclaimer', models.TextField(default='Este conteúdo tem caráter exclusivamente educacional e informativo. Não constitui recomendação de investimento, oferta ou análise personalizada. Decisões de investimento devem ser tomadas com apoio de profissional certificado pela CVM, considerando o perfil individual do investidor.')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho (gerado por IA)'), ('em_revisao', 'Em revisão humana'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('modelo_ia', models.CharField(blank=True, max_length=80)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_educacionais', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'relatório educacional',
                'verbose_name_plural': 'relatórios educacionais',
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ano', 'mes'), name='relatorio_unico_por_mes_tenant')],
            },
        ),
    ]
