# Generated by Django 6.1 on 2026-08-18 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorMensal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('selic_meta_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('selic_variacao_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ipca_mes_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ipca_12m_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fonte', models.CharField(default='Banco Central do Brasil (SGS)', max_length=120)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'indicador mensal',
                'verbose_name_plural': 'indicadores mensais',
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='indicador_unico_por_mes')],
            },
        ),
    ]
