# Generated by Django 6.1 on 2026-08-14 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('retrato_financeiro', 'Retrato financeiro (self-service)'), ('revisao_consultoria', 'Revisão de consultoria (Fase 2)')], default='retrato_financeiro', max_length=25)),
                ('referencia_ano', models.PositiveIntegerField()),
                ('referencia_mes', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('arquivo', models.FileField(blank=True, upload_to='relatorios/%Y/%m/')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='households.household')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'relatório do cliente',
                'verbose_name_plural': 'relatórios do cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
