# Generated by Django 6.1 on 2026-08-14 12:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=180)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_alvo', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='households.household')),
                ('membro', models.ForeignKey(blank=True, help_text='Nulo = meta familiar/compartilhada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='households.member')),
                ('objetivo', models.ForeignKey(blank=True, help_text='Vínculo opcional com um objetivo de vida do onboarding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='households.lifegoal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['data_alvo', 'descricao'],
            },
        ),
    ]
